foxssake/netfox

- addons/netfox.noray/noray.gd
- addons/netfox.noray/packet-handshake.gd
- addons/netfox.noray/plugin.cfg
- addons/netfox.noray/protocol-handler.gd
- addons/netfox/network-events.gd
- addons/netfox/network-rollback.gd
- addons/netfox/network-time-synchronizer.gd
- addons/netfox/network-time.gd
- addons/netfox/plugin.cfg
- addons/netfox/rollback-synchronizer.gd
- examples/multiplayer-netfox/multiplayer-netfox.tscn
- project.godot
> doc: Add documentation comments

- examples/forest-brawl/scripts/name-provider.gd
> fix: Player name out of bounds

- addons/netfox.noray/plugin.cfg
- addons/netfox/network-time-synchronizer.gd
- addons/netfox/network-time.gd
- addons/netfox/plugin.cfg
- examples/forest-brawl/scripts/displacer.gd
- examples/forest-brawl/scripts/effects/effect.gd
- examples/forest-brawl/scripts/powerup.gd
- examples/forest-brawl/scripts/score-manager.gd
- examples/forest-brawl/scripts/weapon.gd
> feat: NetworkTime utils

- addons/netfox.extras/base-net-input.gd
- addons/netfox.extras/netfox-extras.gd
- addons/netfox.extras/plugin.cfg
- addons/netfox.noray/plugin.cfg
- addons/netfox/plugin.cfg
- examples/forest-brawl/scripts/brawler-input.gd
- project.godot
- sh/build.sh
Introduces the extras addon with a convenience class for writing rollback-compatible input
Closes #53
> feat: BaseNetInput

- addons/netfox.extras/plugin.cfg
- addons/netfox.noray/plugin.cfg
- addons/netfox/plugin.cfg
- addons/netfox/rollback/network-rollback.gd
- addons/netfox/rollback/rollback-synchronizer.gd
- examples/forest-brawl/scripts/effects/effect.gd
> refactor: Rename notify_earliest_input to notify_resimulation_start

- docs/assets/netfox.svg
- docs/index.md
- mkdocs.yml
> doc: Setup site with mkdocs

- docs/index.md
- docs/tutorials/ticking-in-sync.md
> doc: NetworkTime tutorial

- addons/netfox.extras/plugin.cfg
- addons/netfox.noray/plugin.cfg
- addons/netfox/network-time-synchronizer.gd
- addons/netfox/plugin.cfg
- docs/guides/network-time-synchronizer.md
- docs/guides/network-time.md
- mkdocs.yml
> doc: Add NetworkTimeSynchronizer guide

- addons/netfox.extras/plugin.cfg
- addons/netfox.noray/plugin.cfg
- addons/netfox/plugin.cfg
- docs/guides/interpolators.md
- mkdocs.yml
> doc: Add Interpolators guide

- addons/netfox.extras/plugin.cfg
- addons/netfox.noray/plugin.cfg
- addons/netfox/plugin.cfg
- docs/guides/property-paths.md
- docs/nodes/tick-interpolator.md
- mkdocs.yml
> doc: Add TickInterpolator

- addons/netfox.extras/plugin.cfg
- addons/netfox.noray/plugin.cfg
- addons/netfox/network-time.gd
- addons/netfox/plugin.cfg
> fix: No tick_factor with sync_to_physics

- addons/netfox.extras/base-net-input.gd
- addons/netfox.extras/plugin.cfg
- addons/netfox.noray/plugin.cfg
- addons/netfox/plugin.cfg
- docs/netfox.extras/guides/base-net-input.md
- mkdocs.yml
> doc: Add BaseNetInput guide

- docs/netfox/concepts/authoritative-servers.md
- mkdocs.yml
> doc: Authoritative servers

- docs/netfox/concepts/servers-clients-ownership.md
- docs/netfox/nodes/rollback-synchronizer.md
- mkdocs.yml
> doc: Ownership

- README.md
- addons/netfox.extras/README.md
- addons/netfox.noray/README.md
- addons/netfox/README.md
- docs/index.md
> doc: Update links

- README.md
> doc: Add contribution notes

- README.md
- docs/index.md
> doc: Enable addons section

- addons/netfox.extras/plugin.cfg
- addons/netfox.noray/plugin.cfg
- addons/netfox/interpolators.gd
- addons/netfox/netfox.gd
- addons/netfox/plugin.cfg
- project.godot
> refactor: Make Interpolators a static class

- addons/netfox.extras/plugin.cfg
- addons/netfox.noray/plugin.cfg
- addons/netfox/plugin.cfg
- addons/netfox/rollback/rollback-synchronizer.gd
- examples/forest-brawl/scripts/brawler-controller.gd
> chore: Add RollbackSynchronizer class name

- docs/netfox/tutorials/rollback-caveats.md
Minor thing but it's good to see the exact progress by clicking/reading that (as a user)
> Documentation - Reference the issue which will solve multiple physics steps preventing instant rollback

- addons/netfox/network-time.gd
Solves https://github.com/foxssake/netfox/issues/186
> Deleted outdated tutorial link in comment

- addons/netfox.extras/plugin.cfg
- addons/netfox.internals/plugin.cfg
- addons/netfox.noray/noray.gd
- addons/netfox.noray/plugin.cfg
- addons/netfox.noray/protocol-handler.gd
- addons/netfox/network-time.gd
- addons/netfox/plugin.cfg
- addons/netfox/rollback/network-rollback.gd
- addons/netfox/rollback/rollback-freshness-store.gd
- addons/netfox/rollback/rollback-synchronizer.gd
> chore: Add type annotations where sensible

- docs/netfox/tutorials/responsive-player-movement.md
> doc: Add process_settings note to ownership in rollback tutorial

- addons/netfox.extras/plugin.cfg
- addons/netfox.internals/plugin.cfg
- addons/netfox.noray/plugin.cfg
- addons/netfox/netfox.gd
- addons/netfox/network-performance.gd
- addons/netfox/plugin.cfg
- docs/netfox/guides/network-performance.md
- mkdocs.yml
- project.godot
Implements NetworkPerformance autoload, that provides custom monitors for networking performance measurements.
Refs #173
> feat: Performance monitors

- addons/netfox.extras/plugin.cfg
- addons/netfox.internals/plugin.cfg
- addons/netfox.noray/plugin.cfg
- addons/netfox/plugin.cfg
- addons/netfox/rollback/rollback-synchronizer.gd
- docs/netfox/nodes/rollback-synchronizer.md
> feat: Enable updating authority on RollbackSynchronizer

- addons/netfox.extras/plugin.cfg
- addons/netfox.internals/plugin.cfg
- addons/netfox.noray/plugin.cfg
- addons/netfox/plugin.cfg
- addons/netfox/properties/property-entry.gd
- docs/netfox/guides/property-paths.md
> feat: Support nested properties

- addons/netfox.extras/plugin.cfg
- addons/netfox.extras/weapon/network-weapon.gd
- addons/netfox.internals/plugin.cfg
- addons/netfox.noray/plugin.cfg
- addons/netfox/plugin.cfg
> fix: Make sure generated projectile ID's are unique

- addons/netfox.extras/plugin.cfg
- addons/netfox.extras/weapon/network-weapon.gd
- addons/netfox.internals/plugin.cfg
- addons/netfox.noray/plugin.cfg
- addons/netfox/plugin.cfg
> fix: Projectiles can be spawned without ID

- addons/netfox.extras/plugin.cfg
- addons/netfox.internals/plugin.cfg
- addons/netfox.noray/plugin.cfg
- addons/netfox/plugin.cfg
- addons/netfox/rollback/network-rollback.gd
#252
Prevent values lower than 1 as they can break netfox.
> Guard input redundancy from values less than one

- README.md
- docs/index.md
> doc: Add supported versions

- docs/netfox/nodes/rollback-synchronizer.md
- docs/netfox/nodes/tick-interpolator.md
- docs/netfox/tutorials/interpolation-caveats.md
- docs/netfox/tutorials/rollback-caveats.md
- mkdocs.yml
> doc: Add Interpolation caveats

- addons/netfox.extras/plugin.cfg
- addons/netfox.internals/plugin.cfg
- addons/netfox.noray/plugin.cfg
- addons/netfox/plugin.cfg
- addons/netfox/rollback/rollback-synchronizer.gd
> fix: Use record input props instead of auth

- addons/netfox.extras/plugin.cfg
- addons/netfox.internals/plugin.cfg
- addons/netfox.noray/plugin.cfg
- addons/netfox/plugin.cfg
- addons/netfox/rollback/network-rollback.gd
- addons/netfox/rollback/rollback-synchronizer.gd
> fix: Limit rollback ticks

- addons/netfox.extras/plugin.cfg
- addons/netfox.internals/plugin.cfg
- addons/netfox.noray/plugin.cfg
- addons/netfox/plugin.cfg
- examples/multiplayer-simple/multiplayer-simple.tscn
- examples/multiplayer-state-machine/multiplayer-state-machine.tscn
- examples/shared/scripts/lan-bootstrapper.gd
- examples/shared/scripts/noray-bootstrapper.gd
- examples/shared/ui/network-popup.tscn
Solves #328 
@krazyjakee give this PR a try, and do confirm if it fixes the problem.
> fix: host/join signals not emitting at multiplyer-simple-demo and state-machine-demo

- addons/netfox.extras/plugin.cfg
- addons/netfox.extras/weapon/network-weapon-2d.gd
- addons/netfox.extras/weapon/network-weapon-3d.gd
- addons/netfox.extras/weapon/network-weapon.gd
- addons/netfox.internals/plugin.cfg
- addons/netfox.noray/plugin.cfg
- addons/netfox/plugin.cfg
- docs/netfox.extras/guides/network-weapon.md
- examples/forest-brawl/scripts/bomb-projectile.gd
- examples/forest-brawl/scripts/brawler-weapon.gd
> feat: Track fired tick for NetworkWeapon

- addons/netfox.extras/plugin.cfg
- addons/netfox.internals/plugin.cfg
- addons/netfox.noray/plugin.cfg
- addons/netfox/network-events.gd
- addons/netfox/network-time.gd
- addons/netfox/plugin.cfg
- addons/netfox/rollback/network-rollback.gd
> fix: Add logger tags in _ready

- addons/netfox.extras/plugin.cfg
- addons/netfox.internals/plugin.cfg
- addons/netfox.noray/plugin.cfg
- addons/netfox/plugin.cfg
- addons/netfox/properties/property-entry.gd
- examples/multiplayer-fps/scripts/player.gd
> refactor: Use get_property_list() to check property presence

- test/netfox/properties/property-entry.gd
> chore: PropertyEntry tests

- addons/netfox.extras/plugin.cfg
- addons/netfox.internals/logger.gd
- addons/netfox.internals/plugin.cfg
- addons/netfox.noray/plugin.cfg
- addons/netfox/network-events.gd
- addons/netfox/network-time.gd
- addons/netfox/plugin.cfg
- addons/netfox/rollback/network-rollback.gd
> fix: Unregister log tags on game exit

- addons/netfox.extras/plugin.cfg
- addons/netfox.extras/window-tiler.gd
- addons/netfox.internals/logger.gd
- addons/netfox.internals/plugin.cfg
- addons/netfox.noray/plugin.cfg
- addons/netfox/network-time-synchronizer.gd
- addons/netfox/network-time.gd
- addons/netfox/plugin.cfg
- addons/netfox/rollback/network-rollback.gd
- examples/forest-brawl/scripts/brawler-controller.gd
- examples/input-prediction/marble.gd
- examples/multiplayer-fps/scripts/player.gd
- examples/multiplayer-fps/scripts/ui/window-size-connector.gd
- examples/multiplayer-netfox/scripts/player.gd
- examples/multiplayer-simple/scripts/player.gd
- examples/multiplayer-state-machine/scripts/player.gd
- examples/rollback-fps/scripts/player.gd
- examples/single-player/scripts/player.gd
> chore: Cache project settings

- addons/netfox.extras/plugin.cfg
- addons/netfox.extras/state-machine/rewindable-state-machine.gd
- addons/netfox.internals/plugin.cfg
- addons/netfox.noray/plugin.cfg
- addons/netfox/plugin.cfg
- examples/multiplayer-state-machine/multiplayer-state-machine.tscn
Bundle:
[netfox.extras.v1.25.6.zip](https://github.com/user-attachments/files/19719028/netfox.extras.v1.25.6.zip)
[netfox.noray.v1.25.6.zip](https://github.com/user-attachments/files/19719029/netfox.noray.v1.25.6.zip)
[netfox.v1.25.6.zip](https://github.com/user-attachments/files/19719030/netfox.v1.25.6.zip)
> fix: Don't run callbacks in editor for RewindableStateMachine

- addons/netfox.extras/plugin.cfg
- addons/netfox.internals/plugin.cfg
- addons/netfox.noray/plugin.cfg
- addons/netfox/encoder/diff-history-encoder.gd
- addons/netfox/plugin.cfg
- addons/netfox/rollback/rollback-synchronizer.gd
> refactor: Consolidate tick broadcast logic

- docs/netfox/guides/interpolators.md
Kudos to @tldmbruno for the catch!
> doc: Interpolators provided as static class

- addons/netfox.extras/plugin.cfg
- addons/netfox.internals/plugin.cfg
- addons/netfox.noray/plugin.cfg
- addons/netfox/plugin.cfg
- addons/netfox/rollback/composite/rollback-history-transmitter.gd
- addons/netfox/state-synchronizer.gd
> fix: Properly detect whether full or diff state is smaller

- README.md
- addons/netfox.extras/plugin.cfg
- addons/netfox.internals/plugin.cfg
- addons/netfox.noray/plugin.cfg
- addons/netfox/peer-visibility-filter.gd
- addons/netfox/peer-visibility-filter.gd.uid
- addons/netfox/plugin.cfg
- addons/netfox/rollback/composite/rollback-history-transmitter.gd
- addons/netfox/rollback/network-rollback.gd
- addons/netfox/rollback/rollback-synchronizer.gd
- addons/netfox/state-synchronizer.gd
- docs/netfox/guides/visibility-management.md
- examples/multiplayer-netfox/scripts/player.gd
- examples/visibility-filtering/README.md
- examples/visibility-filtering/scenes/player.tscn
- examples/visibility-filtering/scripts/npc.gd.uid
- examples/visibility-filtering/scripts/player-input.gd
- examples/visibility-filtering/scripts/player-input.gd.uid
- examples/visibility-filtering/scripts/player.gd
- examples/visibility-filtering/scripts/player.gd.uid
- examples/visibility-filtering/scripts/visibility-manager.gd
- examples/visibility-filtering/scripts/visibility-manager.gd.uid
- examples/visibility-filtering/visibility-filtering.gd
- examples/visibility-filtering/visibility-filtering.gd.uid
- examples/visibility-filtering/visibility-filtering.tscn
- mkdocs.yml
- test/netfox/peer-visibility-filter.test.gd
- test/netfox/peer-visibility-filter.test.gd.uid
> feat: Visibility filtering
