foxssake/netfox

addons/netfox.noray/plugin.cfg
addons/netfox/plugin.cfg
addons/netfox/rollback-synchronizer.gd
examples/forest-brawl/scripts/tick-interpolator.gd
examples/shared/scripts/time-display.gd
project.godot

Both `RollbackSynchronizer` and `TickInterpolator` used `df` to interpolate - the idea was to calculate a factor based on how much is left from the tick and interpolate between the *current* state and the target state, instead of the *previous* tick state and the target. This promised some leeway in masking simulation artifacts, but `df` turned out to be numerically unstable.
The fix is to simply interpolate between the previous and target tick state without the `df` wizardry.

fix: Interpolation factor

---

examples/forest-brawl/scripts/effects/effect.gd

Issue only happened in Release builds, worked fine in Debug. For some reason, in Release, the `free()` method wasn't found in the Effect class, basically removing all effect classes. This wasn't apparent during gameplay, as the server simulated the effects and synced to the clients.
Switching to `queue_free()` fixed the issue.
Closes #43

fix: Powerup effects stay even after effect ends

---

addons/netfox.noray/plugin.cfg
addons/netfox/plugin.cfg
addons/netfox/rollback/rollback-synchronizer.gd

Include all nodes in rollback simulation that implement the `_rollback_tick` method, instead of only the ones that contain either state or input.
Closes #29

feat: Rollback all aware nodes

---

examples/forest-brawl/scripts/brawler-controller.gd
examples/forest-brawl/scripts/displacer.gd
examples/forest-brawl/scripts/effects/repulse-effect.gd

In some cases, the players can get caught up in their own blast zones. When they fall after this, the score manager will award an extra point to whoever hit them last - which is the player itself. This is fixed by adding some extra checks, and an additional error message in case this happens.
Refs #48

fix(game): Players getting points for hitting themselves

---

examples/forest-brawl/scripts/bomb-projectile.gd

The issue was the misunderstanding of ShapeCast's target_position variable. Turns out it's relative to the node, similarly as a child node would be.
Closes #83

fix(game): Weird bomb collisions

---

addons/netfox.extras/plugin.cfg
addons/netfox.extras/weapon/network-weapon.gd
addons/netfox.noray/plugin.cfg
addons/netfox/plugin.cfg

Clients spawning other clients' projectiles did not call the `_after_fire` hook, which meant that weapon firing effects were not replicated to anyone other than the host and the client that fired it.
Closes #89

fix: NetworkWeapon not calling after fire hook

---

examples/forest-brawl/scripts/brawler-input.gd

Prefers gamepad, only considers mouse when actually in use. After a mouse motion, will linger for a bit on mouse, then switch back to gamepad. Uses movement direction if no aim input is given.
Closes #107

feat(game): Improved aiming

---

addons/netfox.extras/plugin.cfg
addons/netfox.extras/weapon/network-weapon-2d.gd
addons/netfox.extras/weapon/network-weapon-3d.gd
addons/netfox.noray/plugin.cfg
addons/netfox/plugin.cfg

Projectiles would spawn and then disappear shortly after on client machines. The issue was a too small threshold for projectile reconciliation, which was raised to a more reasonable default.
Closes #119

fix: Projectile reconciliation threshold

---

examples/multiplayer-simple/characters/player.tscn
examples/multiplayer-simple/multiplayer-simple.tscn

I ran into two issues when taking a look at the simple example.
First, connect_ui wasn't set in either of the bootstrappers:
Second, players would fly away when spawning inside each other. I can sometimes get them to fall down again by moving them around, but I didn't manage to make that work in the video showcasing the issue:
https://github.com/foxssake/netfox/assets/97706756/abc8ddf8-cc59-477c-b9ff-0884a9d465ed
This pull request fixes both issues by setting connect_ui and making it so players don't collide with each other. You can see the fixes in action here:
https://github.com/foxssake/netfox/assets/97706756/48c6e05f-0e31-40a8-8212-26b9e203e4ee

fix: Problems with multiplayer-simple example

---

examples/multiplayer-netfox/characters/player.tscn
examples/multiplayer-netfox/multiplayer-netfox.tscn
examples/multiplayer-netfox/scripts/player.gd

I ran into three issues when taking a look at the netfox example.
First, the connect_ui issue mentioned in #134 showed up here as well. I applied the same fix.
Second, I noticed that the player's `_tick` function wasn't getting called. It looks like it should be connected to `NetworkTime`'s `on_tick` signal, so I went ahead and did that as a fix.
Third, I can't get the players to move and haven't figured out why. The input works and `velocity` is set, but nothing noticeable happens when `move_and_slide` is called. Hopefully you'll know what needs to be done to fix this, and then the fix can be part of this or a different pull request.
Oh also, Godot automatically removed a line from `player.tscn`  and I thought it was relevant enough to be part of this pull request.

fix: Problems with multiplayer-netfox example

---

.gitignore
addons/netfox.extras/plugin.cfg
addons/netfox.noray/plugin.cfg
addons/netfox/plugin.cfg
sh/build.sh

When installed from Godot's AssetLib tab, addons are installed to the project root, instead of the addons directory. Looking at other addons, it looks like the root folder isn't addons, but `<addon-name>-<hash>`. Doing the same for netfox should solve this issue.
Note that there's no known way to validate this locally, so further PRs might be needed.
Refs #140

fix: Addon installed to project root

---

README.md
addons/netfox.noray/README.md
docs/index.md
sh/build.sh

In reality, netfox.noray can be used alone. Removed the with-deps version from builds and updated docs.
Closes #142

fix: Remove netfox.noray dependency on netfox

---

examples/shared/scripts/noray-bootstrapper.gd

fix(examples): Noray bootstrapper refuse connection on empty role

---

addons/netfox/network-time.gd

>https://foxssake.github.io/netfox/tutorials/ticking-in-sync/
Btw on the line above this pull request's change, I do not know where it directs. I would love to read the latest part.

Redirect dead link (error 404) to proper documentation link

---

docs/netfox.extras/guides/network-weapon.md

Btw, the reconcilation is not crystal clear:
>Since the server's state is the source of truth, the projectile's local state will be updated with the difference. This is called reconciliation.
The projectile's local state on the client who first spawned it, or the server? Also what is the difference, what is it measured in?

Documentation - 1 typo

---

examples/forest-brawl/scripts/effects/effect.gd

Powerup effects forced rollback from the tick they were spawned to ensure they are applied correctly. This was done through the whole lifetime of the effect, which lead to excessive rollback and potential perf drops.
Rollback is forced once to ensure the effect is applied, but only once.

fix(game): Excessive rollback when an Effect is active

---

addons/netfox.extras/plugin.cfg
addons/netfox.internals/plugin.cfg
addons/netfox.noray/plugin.cfg
addons/netfox/icons/rollback-synchronizer.svg
addons/netfox/icons/state-synchronizer.svg
addons/netfox/icons/tick-interpolator.svg
addons/netfox/plugin.cfg

Godot has a bug where small SVG icons aren't scaled up when the editor is.
This results in a minor icon issue on the scene tree.
Of course, the best fix is an upstream fix to the editor itself, but pending that, scaling up the icons seems to do the trick.
This works on both 100% and 200% scaling.

fix: hdpi svg icons

---

addons/netfox.extras/plugin.cfg
addons/netfox.internals/plugin.cfg
addons/netfox.noray/plugin.cfg
addons/netfox/netfox.gd
addons/netfox/plugin.cfg
addons/netfox/rollback/network-rollback.gd
addons/netfox/rollback/rollback-synchronizer.gd
docs/netfox/guides/network-rollback.md

Switches input rpcs to be unreliable but with redundancy.
The idea is we don't want a single lost or out of order packet to jam up the flow of our game. Something that becomes increasingly likely the more players you have or the faster you dial up the tick rate.
This simple change dramatically improved response times in my test games and stopped states of 'rollback choking' as Enet tries to recover from a packet discrepancy.
The other benefit is now UDP packets race to provide the next tick info at the cost of slightly more data.
Tested with upto 20% packet loss and game remained stable. At higher packet loss rates Enet kills the connection.
Relevant discussion: https://github.com/foxssake/netfox/discussions/194
How Enet works when set to …

Unreliable inputs with redundancy

---

addons/netfox.extras/plugin.cfg
addons/netfox.internals/plugin.cfg
addons/netfox.noray/plugin.cfg
addons/netfox/plugin.cfg
addons/netfox/properties/property-entry.gd

When using the netfox synchronizers, nested properties were being read and serialized correctly, but on the receiving end, the data would silently fail to be applied to the synced node because the function `set_value()` in property-entry.gd was using `node.set()` instead of `node.set_indexed()`

Fix nested properties not being applied

---

addons/netfox.extras/plugin.cfg
addons/netfox.internals/plugin.cfg
addons/netfox.noray/plugin.cfg
addons/netfox/network-time.gd
addons/netfox/plugin.cfg
docs/netfox/guides/network-time.md

Use OS time for tick loop to avoid time drifting between clients. Also supports pausing both from editor and via SceneTree.pause.
Refs #177

feat: Use OS time for tick loop

---

addons/netfox.extras/plugin.cfg
addons/netfox.internals/logger.gd
addons/netfox.internals/plugin.cfg
addons/netfox.noray/plugin.cfg
addons/netfox/plugin.cfg

Example logs with the new format:
```
[DBG][@124][#1][netfox::NetworkTime] Client #384545578 is now on time!
[INF][@140][#1][netfox.extras::NetworkWeapon] [1] Accepting projectile df4k0e3r73f2 from 1
[DBG][@137][#384545578][netfox.extras::NetworkWeapon] Calling after fire hook for Bomb Projectile df4k0e3r73f2
[INF][@138][#384545578][netfox.extras::NetworkWeapon] [384545578] Accepting projectile df4k0e3r73f2 from 1
[INF][@152][#1][netfox.extras::NetworkWeapon] [1] Accepting projectile s10skmcayltj from 1
[DBG][@149][#384545578][netfox.extras::NetworkWeapon] Calling after fire hook for Bomb Projectile s10skmcayltj
[INF][@150][#384545578][netfox.extras::NetworkWeapon] [384545578] Accepting projectile s10skmcayltj from 1
[INF][@164][#1][netfox.extras::NetworkWeapon] [1] Accepting projectile …
```

chore: Add tick and peer id to logging

---

docs/netfox/tutorials/rollback-caveats.md

Updating docs with some notes on caveats based on recent chats

Added notes to caveats

---

addons/netfox.extras/plugin.cfg
addons/netfox.internals/plugin.cfg
addons/netfox.noray/plugin.cfg
addons/netfox/plugin.cfg
addons/netfox/tick-interpolator.gd

At the end of the tick loop, `TickInterpolator` catches the new state and starts interpolating towards it. However, between `NetworkTime.after_tick_loop` and the next `TickInterpolator._process` callback, there may be a single frame where the interpolated node(s) are still in the target state, and then get set back to the starting state once the interpolation kicks in. This leads to a periodic glitching.
To fix this, `TickInterpolator` always applies the starting state once it's captured, in `NetworkTime.after_tick_loop`.
Closes #287

fix: TickInterpolator glitch on state switch

---

addons/netfox.extras/plugin.cfg
addons/netfox.internals/plugin.cfg
addons/netfox.noray/plugin.cfg
addons/netfox/plugin.cfg
addons/netfox/properties/property-snapshot.gd
addons/netfox/rollback/rollback-synchronizer.gd
addons/netfox/state-synchronizer.gd
addons/netfox/tick-interpolator.gd

refactor: Expand variable names

---

addons/netfox.extras/plugin.cfg
addons/netfox.internals/logger.gd
addons/netfox.internals/plugin.cfg
addons/netfox.noray/plugin.cfg
addons/netfox/plugin.cfg

Recently the default log level setting was changed from *All* to *Debug*. Since the project used these default values, they were not written to disk. 
However, when these values were retrieved with `ProjectSettings.get_setting`, the default was specified as *All*. So the project settings contained the ( default ) value of *Debug*, which was not saved ( since it had the default value ), and then read as *All*.
Fixes #330

fix: Log levels

---

addons/netfox.extras/plugin.cfg
addons/netfox.extras/state-machine/rewindable-state-machine.gd
addons/netfox.extras/weapon/network-weapon.gd
addons/netfox.extras/window-tiler.gd
addons/netfox.internals/logger.gd
addons/netfox.internals/plugin.cfg
addons/netfox.noray/noray.gd
addons/netfox.noray/plugin.cfg
addons/netfox/network-time-synchronizer.gd
addons/netfox/network-time.gd
addons/netfox/plugin.cfg
addons/netfox/properties/property-cache.gd
addons/netfox/rollback/network-rollback.gd
addons/netfox/rollback/rollback-synchronizer.gd

refactor: Conditional log message evaluation

---

addons/netfox.extras/plugin.cfg
addons/netfox.internals/logger.gd
addons/netfox.internals/plugin.cfg
addons/netfox.noray/plugin.cfg
addons/netfox/network-events.gd
addons/netfox/network-time.gd
addons/netfox/plugin.cfg

Directly referencing `NetworkTime` and `NetworkEvents` in `_NetfoxLogger` means that `netfox.internals` depends on `netfox`. This creates both a circular dependency, and an unnecessary dependency for `netfox.noray`. The noray integration doesn't need netfox itself to work properly, and should be kept usable *without* netfox itself. 
Instead, tags can be registered in `_NetfoxLogger`, which are functions that provide information for all log messages. Tags are ordered, to ensure the same log message format, regardless of the order the registering may run their init functions.

refactor: NetfoxLogger no longer depends on netfox

---

examples/forest-brawl/scenes/effects/mass-effect.tscn
examples/forest-brawl/scenes/effects/repulse-effect.tscn
examples/forest-brawl/scenes/effects/speed-effect.tscn
examples/forest-brawl/scripts/effects/effect.gd

Repulse effect's radius is difficult to judge based on the aura alone. This PR adds an emissive decal to effects so they are projected onto the ground as well:
Also removes the procedural animation code and uses an AnimationPlayer instead to manage effect birth and death animations.

feat(game): Aura decals

---

addons/netfox.extras/plugin.cfg
addons/netfox.internals/plugin.cfg
addons/netfox.noray/plugin.cfg
addons/netfox/interpolators.gd
addons/netfox/plugin.cfg

fix: Add missing interpolators

---

addons/netfox.extras/plugin.cfg
addons/netfox.internals/plugin.cfg
addons/netfox.noray/plugin.cfg
addons/netfox/plugin.cfg
examples/forest-brawl/forest-brawl.tscn
examples/multiplayer-fps/multiplayer-fps.tscn
examples/multiplayer-netfox/multiplayer-netfox.tscn
examples/multiplayer-simple/multiplayer-simple.tscn

As far as I can tell, these are unused.
I'm guessing they probably can't be used safely with netfox as they aren't rollback-aware. Remove these to avoid confusion about how players are spawned.

chore: Remove MultiplayerSpawner from examples

---

addons/netfox.extras/plugin.cfg
addons/netfox.internals/plugin.cfg
addons/netfox.noray/plugin.cfg
addons/netfox/plugin.cfg
addons/netfox/rollback/network-rollback.gd
project.godot

Log messages now include rollback tick, range, and stage ( B - before loop, P - prepare, S - simulate, R - record, A - after loop ):
```
[INF][@66][#1][S@65|65>66][fb::Brawler] Biiiiig jump!
[INF][@90][#1][S@89|89>90][fb::Brawler] Biiiiig jump!
[INF][@114][#1][S@113|113>114][fb::Brawler] Biiiiig jump!
[INF][@138][#1][S@137|137>138][fb::Brawler] Biiiiig jump!
[INF][@162][#1][S@161|161>162][fb::Brawler] Biiiiig jump!
[INF][@186][#1][S@185|185>186][fb::Brawler] Biiiiig jump!
[INF][@210][#1][S@209|209>210][fb::Brawler] Biiiiig jump!
```

chore: Log rollback stage and range

---

addons/netfox.extras/plugin.cfg
addons/netfox.internals/plugin.cfg
addons/netfox.noray/plugin.cfg
addons/netfox/plugin.cfg
addons/netfox/rollback/rollback-synchronizer.gd

fix: Send state ack's to sender instead of authority

---

addons/netfox.extras/plugin.cfg
addons/netfox.internals/history-buffer.gd
addons/netfox.internals/plugin.cfg
addons/netfox.noray/plugin.cfg
addons/netfox/plugin.cfg
addons/netfox/properties/property-history-buffer.gd
test/netfox.internals/history-buffer.gd

`_HistoryBuffer.get_snapshot()` was returning `_PropertySnapshot.new()` if unable to find the relevant tick. While this is useful for the specific `_PropertyHistoryBuffer` implementation, it shouldn't be the default for the generic implementation.
- Fixed return data to be in line with generic `_HistoryBuffer` implementation, added specific return data to `_PropertyHistoryBuffer`.

fix: _HistoryBuffer snapshot return 

---

addons/netfox.extras/plugin.cfg
addons/netfox.extras/window-tiler.gd
addons/netfox.internals/plugin.cfg
addons/netfox.noray/plugin.cfg
addons/netfox/plugin.cfg

Godot 4.4 brings in embedded running inside the editor.
This breaks tiling as both floating and embedded run modes can't be moved or resized.
This fix checks if the window is embedded and if so doesn't count itself towards the tiling totals or attempts to change any window settings.
Relevant Godot PR: https://github.com/godotengine/godot/pull/99010

fix: Don't tile if embedded in editor

---

addons/netfox.extras/plugin.cfg
addons/netfox.internals/bimap.gd
addons/netfox.internals/plugin.cfg
addons/netfox.noray/plugin.cfg
addons/netfox/encoder/diff-history-encoder.gd
addons/netfox/encoder/redundant-history-encoder.gd
addons/netfox/encoder/snapshot-history-encoder.gd
addons/netfox/plugin.cfg
addons/netfox/properties/property-config.gd
addons/netfox/rollback/rollback-synchronizer.gd
examples/shared/scripts/time-display.gd
test/netfox.internals/bimap.test.gd
test/netfox/encoder/diff-history-encoder.test.gd
test/netfox/encoder/redundant-history-encoder.test.gd
test/netfox/encoder/snapshot-history-encoder.test.gd
test/netfox/properties/property-config.test.gd
test/snapshot-fixtures.gd

Removes the property paths from the sent state and input data. Instead:
- SnapshotHistoryEncoder: For full states, simply send an array of values - 104 bytes -> 48 bytes
- DiffHistoryEncoder: For diff states, send a single byte property index and then property value - 44 bytes -> ~~28~~ 32 bytes
- RedundantHistoryEncoder: Send a flattened array of input values - 248 bytes -> 80 bytes
Refs #358 
Closes #159

perf: Reduce encoder bandwidth

---

docs/netfox/nodes/rollback-synchronizer.md
docs/netfox/tutorials/responsive-player-movement.md

I'm trying out Netfox and was confused why my velocity was suddenly infinite. I eventually double checked the caveats page and saw that I'd miss the `/=` line after my call to `move_and_slide()`. 
Changing all of the docs to consistently do the divide after calling `move_and_slide()` will help others avoid stubbing their toes on this as they try out Netfox.
I guess this results in 3 extra float divides per `_rollback_tick` call if your game *does *reset `velocity` for each tick, but that seems like a less common usage since move_and_slide alters `velocity` on collision to implement the "slide" behavior.

doc: Use physics_factor in all example snippets

---

addons/netfox.extras/plugin.cfg
addons/netfox.internals/plugin.cfg
addons/netfox.noray/plugin.cfg
addons/netfox/network-time-synchronizer.gd
addons/netfox/plugin.cfg

`NetworkTimeSynchronizer` samples the host's clock and takes a weighted average of the clock offsets, based on the roundtrip time. If the roundtrip time is very close to zero, the weight itself will zero, thus resulting in a division by zero. This value is then used to adjust the clock, setting it to NaN. This blocks the network tick loop.
To fix this, a check is added that will avoid the weighted average if the RTT is too low, and calculates a regular average instead.
Try the addon: [netfox.v1.26.2.zip](https://github.com/user-attachments/files/20723093/netfox.v1.26.2.zip)

fix: Avoid NaNs at very low latencies

---

addons/netfox.extras/plugin.cfg
addons/netfox.internals/plugin.cfg
addons/netfox.noray/packet-handshake.gd
addons/netfox.noray/plugin.cfg
addons/netfox/plugin.cfg
docs/netfox.noray/guides/packet-handshake.md
examples/shared/scripts/noray-bootstrapper.gd
examples/shared/scripts/time-display.gd

Hello, I have been using the Noray add-on for the last couple of days and I noticed a small issue regarding the method `PacketHandshake.over_enet()`.
I have been using this method in a similar matter to the bootstrapper example:  The host peer uses it to handshake each client peer anytime a NAT or Relay connection is received by Noray.
In my game, the issue appears when the host peer decides to close the "multiplayer lobby" (and thus disconnect from the Noray orchestrator server and freeing its multiplayer_peer)  while a client peer was trying to connect. 
The debugger console in Godot then gets full of error messages for the remaining duration of the timeout while loop in `PacketHandshake.over_enet()` as the connection is no longer active.
```
E 0:00:08:216   packet-handshake.gd:78 @ …
```

feat: Implement handshake over ENetMultiplayerPeer to detect closed connections

---

addons/netfox.extras/plugin.cfg
addons/netfox.internals/plugin.cfg
addons/netfox.noray/plugin.cfg
addons/netfox/encoder/snapshot-history-encoder.gd
addons/netfox/plugin.cfg
test/netfox/encoder/snapshot-history-encoder.test.gd

SnapshotHistoryEncoder was producing warnings:
```
W 0:00:01:0448   logger.gd:137 @ warning(): [WRN][@0][#1][_][netfox::_SnapshotHistoryEncoder] Received snapshot with 4 entries, with 3 known - parsing as much as possible
```
This was not expected, as the snapshot was decoded with the same properties as it was encoded with.

fix: SnapshotHistoryEncoder size mismatch

---

.gitignore
docs/netfox/tutorials/input-gathering-tips-and-tricks.md
examples/snippets/input-gathering-tutorial/continuous-sampled-input.gd
examples/snippets/input-gathering-tutorial/continuous-sampled-input.gd.uid
examples/snippets/input-gathering-tutorial/one-off-input.gd
examples/snippets/input-gathering-tutorial/one-off-input.gd.uid
mkdocs.yml
test/examples/snippets/input-gathering-tutorial/one-off-input.test.gd
test/examples/snippets/input-gathering-tutorial/one-off-input.test.gd.uid
test/network-mocks.gd

Uses the snippets extension to copy example code from a .gd file into the docs. This enables writing tests for the example code.
Closes #489

fix: One-Off Inputs tutorial duplicates one-off input during lag

---

addons/netfox.extras/plugin.cfg
addons/netfox.internals/plugin.cfg
addons/netfox.noray/plugin.cfg
addons/netfox/plugin.cfg
addons/netfox/rewindable-action.gd

The `range` function in GDScript is exclusive, so we need to increment the latest tick by 1 in order to successfully queue the current tick.
Found this live with elementbound for context

fix: RewindableAction to include ticks at the end of the tickset
